### ISSUE TITLE
DEMO please

### ISSUE THREAD

**Issue by luckylooke** [ajakubo1/CanvasMenu#1]
Is there a demo online? So I can quickly see the example? Thanks

**Comment by ajakubo1** [comment]
You're reading my mind. I've just been working on it. I'll let you know when I have everything set up ;).

**Comment by ajakubo1** [comment]
Managed to put samples at: http://trash.thedimgames.com/CanvasMenu/samples/ for now. Not a lot of it right now. The second one has more advanced usage presented (but without descriptions for now, so you'll have to dig into the code).

**Comment by luckylooke** [comment]
Thank you :+1:
