### ISSUE TITLE
Event handlers support

### ISSUE THREAD

**Issue by michalbe** [ajakubo1/CanvasMenu#15]
If we plan to suport more events that just click (like `onmouseover`, etc.), we can use `.on()` method instead of the `.clickHandler()` what's not very intuitive. This pattern is known from `jQuery`, `Angular`, `KO`, and countless number of frameworks, so it will be easy to use for new users of CanvasMenu.
So example from the first sample:

``` javascript
button.clickHandler(function () {
    alert("You've clicked me!");
});
```

will become:

``` javascript
button.on('click', function () {
    alert("You've clicked me!");
});
```

For now each element can have just one `clickHandler` listener, it would be nicer to have multiple of them, like `addEventListener` compared to `onclick`. I suggest we should introduce `this.events` object, where we'll stack those. So 

``` javascript
Button.prototype.clickHandler = function (handler) {
    this.onclick = handler;
};
```

can be expanded to look more/less like this:

``` javascript
Button.prototype.on = function (eventType, handler) {
    this.events[eventType].push(handler);
};
```

**Comment by ajakubo1** [comment]
I've considered what event types can be added to the button, and came up with the following list of events: `mousedown`, `mouseup`,`mousemove`, `mouseenter`, `mouseleave`. I'm just implementing all of those listeners from that list.

**Comment by ajakubo1** [comment]
ah, I've forgotten about `click`. At first I wanted to bind `click` event to `mouseup` event, but then I saw [this](http://www.quirksmode.org/dom/events/click.html). So... I will prepare a separate event for that.
