### ISSUE TITLE
Remove automagic menu switching from the background

### ISSUE THREAD

**Issue by michalbe** [ajakubo1/CanvasMenu#16]
Setting new menu as a listener to switch between menus is not very clear. Setting a listener that will initiate the menu on fly will be more clear and self explanatory, without unneeded magic happening on the backstage.
So 

``` javascript
optionsButton.clickHandler(optionsMenu);
```

will became:

``` javascript
optionsButton.on('click', optionsMenu.init);
```

This will simplify events handling in the library's code, and give more explicit control to the end user.

**Comment by ajakubo1** [comment]
Unfortunately, after consideration, there is one small problem with this issue, and it's the `Menu.destroy()` function call to deactivate menu. If I write it in suggested manner, then the user should remember to always call `Menu.destroy()` function for `Menu` which should be deactivated. If it's not done, all of the listeners are still there and old `Menu` still requests for animation frames. So I would leave this magic part as-is.

**Comment by michalbe** [comment]
Maybe there should be a global internal object that will store all the menu instances and call `.destroy()` on all of them when new `.init()` is called? Shouldn't be hard to implement.

**Comment by ajakubo1** [comment]
I'll have to think on that a bit :D.

Well I could create an entity to which menu registers by calling init(). And then if I have a second init call and I know that other menu is registered, I call on destroy function and swap them.

But don't you think that it's also magic-like behaviour, all the same? Hidden from the user, I give you that, but magic all the same :).

On a side note, it is really important for users to know, that calling the .destroy() function is important when you swap from menu to game screen ;).

**Comment by ajakubo1** [comment]
This reminded me to add #23 ;).
