### ISSUE TITLE
Change `appendButton` to`append`

### ISSUE THREAD

**Issue by michalbe** [ajakubo1/CanvasMenu#17]
With new elements, `appendButton` method won't have any more sense. Adding Switch component or Radio control using `appendButton` sound strange. I suggest to rename the method to simple `append`

**Comment by ajakubo1** [comment]
After considering #14 - I think that this function should be additionally changed to private (with changed name, as suggested) - I don't see the point of making it public when proposed scoping will be implemented.

**Comment by ajakubo1** [comment]
For now, I've changed `appendButton` function into `add` function. I left the function as public (because of scope issue from #14 - if someone can create button by calling `new CM.Button()` then I see the point of changing its scope to private).

**Comment by michalbe** [comment]
@ajakubo1 this makes sense. I'm :+1: with this.
