### ISSUE TITLE
Simplify configuration objects

### ISSUE THREAD

**Issue by michalbe** [ajakubo1/CanvasMenu#18]
Using `redraw` in all possible places makes the library look heavy. How about removing this from the name of all the configurable variables?
So instead of:

``` javascript
var newGameButton = new Button({
    x: 200,
    y: 280,
    width: buttonWidth,
    height: buttonHeight,
    text: "New Game",
    redrawInactiveColor: '#FFFF00',
    redrawFocusedColor: '#660033',
    redrawDownColor: '#FF0033',
    redrawUpColor: '#330033',
    redrawInactiveFont: '#111111',
    redrawDownFont: '#111111',
    font: (buttonHeight * 2 / 5 ) + 'pt Courier'
});
```

we'll have:

``` javascript
var newGameButton = new CM.Button({
    x: 200,
    y: 280,
    width: buttonWidth,
    height: buttonHeight,
    text: "New Game",
    idleColor: '#FFFF00',
    hoverColor: '#660033',
    activeColor: '#FF0033',
    upColor: '#330033',
    idleFont: '#111111',
    downFont: '#111111',
    font: (buttonHeight * 2 / 5 ) + 'pt Courier'
});
```

Names like `inactive`, `focused`, `down` and `up` are not very intuitive. Maybe `idle`, `hover`, `active` (like in CSS) and (... something else for `up` but I have no idea what for now) sound better? And maybe instead of configuring font & color as two attributes, we can use the object? like this:

``` javascript
var newGameButton = new CM.Button({
    x: 200,
    y: 280,
    width: buttonWidth,
    height: buttonHeight,
    text: "New Game",
    idle: {
        color: '#FFFF00',
        font: ' #111111'
    },
    hover: {
        color: '#FFFF00',
        font: ' #111111'
    },
    active: {
        color: '#FFFF00',
        font: ' #111111'
    },
    up: {
        color: '#FFFF00',
        font: ' #111111'
    },
    font: (buttonHeight * 2 / 5 ) + 'pt Courier'
});
```

Methods could be added in the same way:

``` javascript
    idle: {
        color: '#FFFF00',
        font: ' #111111',
        fn: new RedrawIdleButton() // fn, event, method, or even 'before' or 
                                   // 'after' will work as a name here
    },
```

**Comment by ajakubo1** [comment]
Can't think of anything more fitting then 'up' state, but I'm worried about consistency of the whole naming system. Alternative may be just changing it to: `idle`, `over`, `down`, `up` - it may be more consistent and - still - quite intuitive. I agree that `focused` and `inactive` doesn't tell much at a first glance and should be abandoned :).

The configuration nesting idea looks really great, I'm on it ;).

**Comment by ajakubo1** [comment]
Those changes simplify `Button` code a lot.
