### ISSUE TITLE
Divide the library into separate files

### ISSUE THREAD

**Issue by michalbe** [ajakubo1/CanvasMenu#20]
I think main `Menu` constructor with it's logic should be separated from all the components logic if we want to support more than just a `Button`. I can write easy concatenation script to build the library (could cause problems on building on different platforms), or use [Grunt](http://gruntjs.com/) or [Gulp](http://gulpjs.com/) (what should be very easy), or we can use external libs like `require` or `browserify` (what will unfortunately make CanvasMenu heavier, but it will be possible to use it in development mode without building on each change).

**Comment by ajakubo1** [comment]
@michalbe that's what I wanted to do, every element (including `Button`) should be in separate files. I want users to decide which components they need, so they won't have any unneeded code.

I think that basically, when we are testing-out some new code, we don't really need to generate the compressed file, so I think that `require` and `browserify` won't be needed.

And when it comes to grunt or gulp... To tell you the truth I've recently found [this article](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) on the web and wanted to not use those for deployment. Or at least try to write build commands which would be compatible on both windows and linux. I presume, that If build would be made locally, some minifier would be required. [uglifyjs](https://www.npmjs.com/package/uglify-js) supports multiple file input, so we can extract script names from command prompt of build command and send them to uglify. In essence this is something that grunt/gulp would do, right?

**Comment by ajakubo1** [comment]
Hmm... it might not be as simple as I think.

**Comment by ajakubo1** [comment]
In the last commit: b9d2b9e938a8f45be060f58e2e9a6aa4d321abed - I've divided the scripts. I'll put inheritable interface in element.js with functions (changed folder structure a little bit). Made `npm run merge` (merging all of files in src/ into one file in dist/canvasmenu.js, minify it) command and `npm run deploy` (minify all of the scripts in src/).

**Comment by ajakubo1** [comment]
Ok, after some struggle, I've managed to create deploy.js script in the last commit: 609da4c7e102169e99280400850e8d854e25611b. I must say, it runs pretty well and it's not very complicated.

I would have to change it a little bit before publishing npm package, but still, it gets the job done.

You can use it by calling: `npm run deploy -- <element> <element> <element>`. Example:

``` bash
npm run deploy -- menu element button
```

or:

``` bash
npm run deploy -- menu element
```

It creates concatenated file in dist/canvasmenu.js for all of the elements that are needed. Then it minifies selected files into dist/canvasmenu.min.js and dist/canvasmenu.map.

**And it is not foolproof right now, so be carefull what arguments you are using :)**

In order for it to be used with canvas-menu npm package, it should be properly modified. I'll deal with that tomorrow.

**Comment by ajakubo1** [comment]
Currently, you can use deployment script by calling:

``` bash
npm run merge
```

this will extract every element from `src/` to `dist/` and create .min and .map files.

``` bash
npm run deploy
```

this will extract every element from `src/` to root folder and create .min and .map files (users will be able to use it for creating customised canvasmenu.js files).
