### ISSUE TITLE
Avoid global variables

### ISSUE THREAD

**Issue by michalbe** [ajakubo1/CanvasMenu#21]
For now the lib exposes two variables to the global scope - `CM` & `BUTTON_STATES`. It makes no sense at all for me since the latest is used only internally by the BUTTON component. It should be moved somewhere inside it.

**Comment by ajakubo1** [comment]
Yep, ment to do that, but slipped my mind :).

**Comment by ajakubo1** [comment]
Changed the scope to CM. I presume that other elements would have the same states.
