### ISSUE TITLE
Add button type: Switch

### ISSUE THREAD

**Issue by ajakubo1** [ajakubo1/CanvasMenu#8]
New button type: boolean - just as with other buttons, I want it to make them customizable, with support for adding animations

**Comment by michalbe** [comment]
Since `Boolean` is a name of the datatype in js, maybe it would be better to call this component `Switch`

**Comment by ajakubo1** [comment]
Yep, you're right, I think it would be less confusing ;).

**Comment by ajakubo1** [comment]
I've added it (branch for version 2.0.0)
